apiVersion: composition.krateo.io/v0-3-0
kind: AwsRdsStack
metadata:
  name: {{ printf "%s-awsrdsstack" $.Release.Name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $.Release.Namespace }}
spec:
  engine: ""
  identifier: ""
  instance_class: ""
